### ISSUE TITLE
MLX90393 resolution  

### ISSUE THREAD

**Issue by SarwarN88** [adafruit/Adafruit_MLX90393_Library#15]
Hi
I notes in the .cpp file RES=0 and RES=1 has not been defined. However in the .h file they are defined as RES-16 and RES-17. In the data sheet it doesn't provide hex register to call for RES=0 and RES=1. Based on the binary number they both should be 0x0? I just want to know if the library support RES-16 and RES-17 as I can't see them been defined in the .cpp file. Thanks    

![Capture](https://user-images.githubusercontent.com/44071772/106441726-516bca00-6472-11eb-8e1f-911fcf4aa2aa.PNG)
In the .h file they are defined.
![Capture1](https://user-images.githubusercontent.com/44071772/106441819-6f392f00-6472-11eb-8dca-e41510694cdd.PNG)
![Capture2](https://user-images.githubusercontent.com/44071772/106442626-65fc9200-6473-11eb-9f7b-f34b024ffddf.PNG)

**Comment by ladyada** [comment]
unsure what youre asking? enumerations start at 0 so RES_16 is 0x0 and then each one is +1 from taht

**Comment by SarwarN88** [comment]
Thanks for the replay,
I don't see in the .cpp and .h file reference call for RES=0x0, RES=0x1, RES=0x2, RES=0x3? Also from the data sheet when for RES=2 is 0x8000 and RES=3 is 0x4000 are those hex registers to setup the resolution? From the picture bellow are those the call for sitting up resolution? I am little bit confused of how you defined the 4 register resolutions call RES 0,1,2 and 3? Thanks again

![Capture](https://user-images.githubusercontent.com/44071772/106519932-f4a0fb80-64d3-11eb-9666-5c97b6098b76.PNG)

**Comment by ladyada** [comment]
you can read about C++ enum types by googling

**Comment by caternuson** [comment]
There are only 2 bits that set resolution for each of the RES_X, RES_Y, or RES_Z axis in the CONF1 (0x02) register:

![image](https://user-images.githubusercontent.com/8755041/106524308-3bbccb80-6497-11eb-9669-fc939e29976c.png)

That's why 0, 1, 2, and 3 can be used to define the resolutions in the enum.

See the code in `Adafruit_MLX90393::setResolution` for how those end up getting masked and shifted and actually written to the register.

**Comment by SarwarN88** [comment]
Thanks caternuson. I have looked at the function enum and how it works. Now I can understand the code better. The section when resolution is set in the `Adafruit_MLX90393::setResolution` is a little bit complex for my understanding though:D.
