### ISSUE TITLE
Should this say DIG instead of DIF?

### ISSUE THREAD

**Issue by thatfellarobin** [adafruit/Adafruit_MLX90393_Library#16]
https://github.com/adafruit/Adafruit_MLX90393_Library/blob/827b133e103b05f3054555ba9d70022209cedfa3/Adafruit_MLX90393.h#L164

**Comment by ladyada** [comment]
yep feel free to submit a PR fix!

**Comment by caternuson** [comment]
Closing. Fixed with a direct edit:
https://github.com/adafruit/Adafruit_MLX90393_Library/commit/26fabbd23317a30fab952c120b4c4d1c02f64c55
