### ISSUE TITLE
Reason for 10ms delay in startSingleMeasurement()

### ISSUE THREAD

**Issue by MaxMaeder** [adafruit/Adafruit_MLX90393_Library#17]
The `startSingleMeasurement()` function calls on the `transceive()` function to start a measurement. `transceive()` takes 5 arguments, the last one being the length of the delay between sending the data and receiving the status byte and optionally other data. When called in `startSingleMeasurement()`, this argument isn't specified, defaulting the delay to 10 ms.

Is there a reason for this delay in this function, or was the argument perhaps forgotten by mistake? I can't find any mention of this delay in the [datasheet](https://www.melexis.com/-/media/files/documents/datasheets/mlx90393-datasheet-melexis.pdf). I have also tested the library in I2C mode without this delay, and the sensor appears to be working correctly.

Thanks for taking a look at this. I can make a PR if necessary.

**Comment by ladyada** [comment]
we probably found it necessary to get the chip to reply consistantly, it has a finicky (iirc) i2c implementation. that said, you're free to send over a tested PR!

**Comment by MaxMaeder** [comment]
Closed by #18.
