### ISSUE TITLE
Wake-Up on Change mode

### ISSUE THREAD

**Issue by jonathanmbradshaw** [adafruit/Adafruit_MLX90393_Library#21]
Guys, this is a 'have you' question, I have just started to look at MLX90393.
I would like to have a play at Wake-Up on Change mode, any experience with this aspect of the chip?
all the best and thanks Jonathan

**Comment by caternuson** [comment]
Please try asking in the forums:
https://forums.adafruit.com/
or by joining the Adafruit Discord server:
http://adafru.it/discord

This is the place for issues with the library code.
