### ISSUE TITLE
Add resolution, filter, and oversampling

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_MLX90393_Library#3]
Requesting on behalf of:
https://forums.adafruit.com/viewtopic.php?f=25&t=167214

Add ability to set/get additional sensor configuration:

- Resolution (RES_XYZ)
- Filter (DIG_FILT)
- Oversampling (OSR)

**Comment by j980m842** [comment]
Please add this functionality. Here is a link to another library for the MLX90393 which has these functionalities for reference:

https://github.com/tedyapo/arduino-MLX90393

Thank you!

**Comment by caternuson** [comment]
@j980m842 Do you know how to checkout and test PR's? If so:
https://github.com/adafruit/Adafruit_MLX90393_Library/pull/12

**Comment by caternuson** [comment]
Done with #12
