### ISSUE TITLE
Update sensitivty table?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_MLX90393_Library#4]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=8&t=168980

Per the current datasheet:
https://www.melexis.com/-/media/files/documents/datasheets/mlx90393-datasheet-melexis.pdf
looks like there has been an update to the sensitivity tables (see below). The current values in the library may need updating as well?

![mlx](https://user-images.githubusercontent.com/8755041/91771822-7fce3c00-eb98-11ea-829f-5310603876e3.jpg)

**Comment by ladyada** [comment]
guess not , wanna do a PR?

**Comment by caternuson** [comment]
sure. looks like there are a couple of issues here i created. i'll try and get setup and work on both.

**Comment by ladyada** [comment]
oki!

**Comment by caternuson** [comment]
Just documenting...

Looks like the current table values came from this c.June-2015 Getting Started app note:
https://www.melexis.com/-/media/files/documents/application-notes/mlx90393-application-note-melexis.pdf
![mlx2](https://user-images.githubusercontent.com/8755041/91886661-88794d80-ec3e-11ea-889d-c300e9f8c3b9.jpg)

The updated values in the most recent (c.2020) datasheet are not only different, but now also depend on HALLCONF setting.

![mlx3](https://user-images.githubusercontent.com/8755041/91887178-456baa00-ec3f-11ea-9e0d-c339bca65e07.jpg)

**Comment by caternuson** [comment]
Fixed with #5
